#spring.datasource.url=jdbc:mysql://localhost:3306/NameOfTheDatabase
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=rootroot
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USERINFO-MICROSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect