#spring.datasource.url=jdbc:mysql://localhost:3306/NameOfTheDatabase
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=rootroot
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#server port is common to all environments,dev,local
server:
  port: 9093


#application name food-catalogue-microservice is common to all environments,datasource, and jpa properties
#change active to local when you want to use the service locally.
spring:
  profiles:
    active: dev
  application:
    name: USERINFO-MICROSERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect